import type { QuizConfig } from "./types";

const option = (id: string, title: string, tagKey?: string, weight = 5) => ({ id, title, tagWeights: tagKey ? [{ tagKey, weight }] : [] });

/** Explicitly test-only configuration used until the Supabase configuration is published. */
export const demoQuizConfig: QuizConfig = {
  settings: { id: "test-master-quiz", title: "ПОДОБРАТЬ МАСТЕРА", description: "Ответьте на 6 коротких вопросов — это займёт около двух минут.", buttonLabel: "Подобрать мастера", resultLimit: 3, minimumMatchPercent: 0, includeRatingBonus: false, includeAvailabilityBonus: false, isActive: true, categoryWeights: { interest: 35, communication: 20, personality: 15, lifestyle: 10, priority: 20 } },
  questions: [
    { id: "service", title: "ЗА КАКОЙ УСЛУГОЙ ВЫ ПЛАНИРУЕТЕ ПРИЙТИ?", questionType: "single_choice", matchingMode: "hard_filter", category: "service", isRequired: true, weight: 1, options: [option("haircut", "Мужская стрижка", "service_haircut"), option("clipper", "Стрижка машинкой", "service_clipper"), option("haircut-beard", "Стрижка и оформление бороды", "service_haircut_beard"), option("beard", "Только борода", "service_beard"), option("shaving", "Бритьё", "service_shaving"), option("care", "Уход за волосами и кожей головы", "service_care"), option("undecided", "Пока не определился")] },
    { id: "interests", title: "КАКИЕ ТЕМЫ ВАМ ИНТЕРЕСНЫ?", description: "Можно выбрать до пяти вариантов", questionType: "limited_multiple_choice", matchingMode: "soft_score", category: "interest", isRequired: false, maxSelections: 5, weight: 1, options: [option("cars", "Автомобили", "interest_cars", 3), option("sport", "Спорт и фитнес", "interest_sport", 3), option("business", "Бизнес и предпринимательство", "interest_business", 3), option("tech", "Технологии и гаджеты", "interest_technology", 3), option("music", "Музыка", "interest_music", 3), option("movies", "Кино и сериалы", "interest_movies", 3), option("games", "Игры", "interest_gaming", 3), option("travel", "Путешествия", "interest_travel", 3), option("fashion", "Мода и стиль", "interest_fashion", 3), option("art", "Искусство и дизайн", "interest_art", 3), option("food", "Еда и рестораны", "interest_food", 3), option("family", "Семья и повседневная жизнь", "interest_family", 3), option("books", "Книги и подкасты", "interest_books", 3), option("no-personal", "Предпочитаю не разговаривать о личном", "communication_quiet", 2)] },
    { id: "lifestyle", title: "КАК ВЫ ЛЮБИТЕ ПРОВОДИТЬ СВОБОДНОЕ ВРЕМЯ?", description: "Можно выбрать до трёх вариантов", questionType: "limited_multiple_choice", matchingMode: "soft_score", category: "lifestyle", isRequired: false, maxSelections: 3, weight: 1, options: [option("sport", "Занимаюсь спортом", "life_sport", 3), option("friends", "Встречаюсь с друзьями", "life_friends", 3), option("projects", "Работаю над своими проектами", "life_projects", 3), option("games", "Играю в компьютерные или настольные игры", "life_games", 3), option("movies", "Смотрю фильмы и сериалы", "life_movies", 3), option("events", "Посещаю концерты и мероприятия", "life_events", 3), option("travel", "Путешествую", "life_travel", 3), option("cars", "Интересуюсь автомобилями", "life_cars", 3), option("family", "Провожу время с семьёй", "life_family", 3), option("books", "Читаю или слушаю подкасты", "life_books", 3), option("quiet", "Предпочитаю спокойный отдых", "life_quiet", 3), option("new", "Постоянно пробую что-то новое", "life_new", 3)] },
    { id: "communication", title: "КАКОЕ ОБЩЕНИЕ С МАСТЕРОМ ВАМ КОМФОРТНЕЕ?", questionType: "single_choice", matchingMode: "soft_score", category: "communication", isRequired: true, weight: 1, options: [option("active", "Люблю активно общаться", "communication_active"), option("easy", "Нравится лёгкий непринуждённый разговор", "communication_easy"), option("quiet", "Предпочитаю спокойствие и минимум разговоров", "communication_quiet"), option("expert", "Хочу больше профессиональных советов", "communication_expert"), option("flexible", "Обычно подстраиваюсь под собеседника", "communication_flexible"), option("neutral", "Для меня это не имеет значения")] },
    { id: "personality", title: "С КАКИМ ЧЕЛОВЕКОМ ВАМ ПРОЩЕ РАССЛАБИТЬСЯ?", description: "Выберите не более двух вариантов", questionType: "limited_multiple_choice", matchingMode: "soft_score", category: "personality", isRequired: false, maxSelections: 2, weight: 1, options: [option("calm", "Спокойным и уравновешенным", "personality_calm"), option("open", "Общительным и открытым", "personality_open"), option("humor", "Весёлым и с хорошим чувством юмора", "personality_humor"), option("professional", "Серьёзным и профессиональным", "personality_professional"), option("energetic", "Энергичным и активным", "personality_energetic"), option("creative", "Творческим и креативным", "personality_creative"), option("confident", "Прямым и уверенным", "personality_confident"), option("any", "Мне подходит любой характер")] },
    { id: "priority", title: "ЧТО ДЛЯ ВАС ВАЖНЕЕ ВСЕГО ПРИ ВЫБОРЕ МАСТЕРА?", description: "Выберите до трёх вариантов", questionType: "limited_multiple_choice", matchingMode: "soft_score", category: "priority", isRequired: true, maxSelections: 3, weight: 1, options: [option("experience", "Большой опыт", "strength_experience"), option("precision", "Аккуратность и внимание к деталям", "strength_precision"), option("creative", "Умение предложить новый образ", "strength_creative"), option("trends", "Понимание современных трендов", "strength_trends"), option("speed", "Скорость работы", "strength_speed"), option("interests", "Общие интересы", "strength_interests"), option("communication", "Комфортное общение", "strength_communication"), option("atmosphere", "Спокойная атмосфера", "strength_atmosphere"), option("care", "Подробные рекомендации по уходу", "strength_care"), option("rating", "Высокий рейтинг", "strength_rating"), option("price", "Доступная стоимость", "strength_price")] },
  ],
  masters: [
    { id: "test-dmitry", name: "Дмитрий", role: "Топ-мастер", rating: 4.9, experienceYears: 6, isActive: true, acceptsNewClients: true, services: ["service_haircut", "service_clipper", "service_haircut_beard", "service_beard"], availability: ["Ближайшее время уточняется"], tagWeights: { interest_cars: 3, interest_sport: 2, interest_business: 3, interest_technology: 2, interest_books: 2, life_sport: 2, life_projects: 3, life_cars: 3, life_books: 2, life_quiet: 2, communication_quiet: 3, communication_expert: 3, communication_flexible: 2, personality_calm: 3, personality_professional: 3, personality_confident: 2, strength_experience: 5, strength_precision: 5, strength_trends: 4, strength_care: 5, strength_rating: 5, strength_communication: 4, strength_atmosphere: 4 } },
    { id: "test-maxim", name: "Максим", role: "Барбер", rating: 4.8, experienceYears: 4, isActive: true, acceptsNewClients: true, services: ["service_haircut", "service_haircut_beard", "service_beard", "service_care"], availability: ["Ближайшее время уточняется"], tagWeights: { interest_sport: 3, interest_music: 3, interest_gaming: 3, interest_technology: 3, interest_travel: 2, interest_fashion: 3, life_sport: 3, life_friends: 3, life_games: 3, life_events: 3, life_travel: 2, life_new: 3, communication_active: 3, communication_easy: 3, communication_flexible: 3, personality_open: 3, personality_humor: 3, personality_energetic: 3, personality_creative: 3, strength_creative: 5, strength_trends: 5, strength_speed: 4, strength_interests: 4, strength_communication: 5 } },
    { id: "test-ivan", name: "Иван", role: "Барбер", rating: 4.9, experienceYears: 5, isActive: true, acceptsNewClients: true, services: ["service_haircut", "service_clipper", "service_haircut_beard", "service_beard", "service_shaving"], availability: ["Ближайшее время уточняется"], tagWeights: { interest_cars: 2, interest_movies: 2, interest_travel: 3, interest_family: 3, interest_food: 2, life_cars: 2, life_movies: 2, life_travel: 3, life_family: 3, life_quiet: 3, communication_quiet: 2, communication_easy: 2, communication_flexible: 3, personality_calm: 3, personality_professional: 3, personality_confident: 3, strength_experience: 4, strength_precision: 5, strength_speed: 4, strength_atmosphere: 5, strength_care: 4, strength_rating: 5 } },
  ],
};
